# Generated by Django 4.2.16 on 2024-11-12 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=127, unique=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("img", models.URLField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pages", models.PositiveIntegerField()),
                ("published_at", models.DateTimeField()),
                ("img", models.URLField(max_length=2047, null=True)),
                ("short_desc", models.TextField(max_length=1023, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookInstace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_due_time", models.DateField(blank=True, null=True)),
                ("maintain_due_time", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a book genre (e.g 'sci-fi')",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="genre",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="genre_name_lower_unique_constrain",
                violation_error_message="Duplicate genre name (NOTE: genre name is case-insensitive)",
            ),
        ),
        migrations.AddField(
            model_name="bookinstace",
            name="book",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.RESTRICT, to="books.book"
            ),
        ),
        migrations.AddField(
            model_name="bookinstace",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="books.author",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(related_name="book", to="books.genre"),
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("fullname"),
                name="author_fullname_lower_unique_constrain",
                violation_error_message="Duplicate author name (NOTE: author name is case-insensitive)",
            ),
        ),
    ]
