# Generated by Django 4.2.16 on 2024-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="img",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
