# Generated by Django 4.2.16 on 2024-11-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_author_img_alter_book_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="authors.image"),
        ),
        migrations.AlterField(
            model_name="book",
            name="img",
            field=models.ImageField(null=True, upload_to="books.image"),
        ),
    ]
